KI:
    priceUnit:
        - USD
    decimalPlace:
        - 2
    updateFreq: 60
    discordBotKey: OTk2MDYxOTM2OTk3Mzc2MTEw.Gp21Yf.ZMJr60lOH563vMUoGj-aUyGYTj4BXkB_0j2OWk
    guildId: 961615648394444860
